### ISSUE TITLE
JDK incompatibility issues with jackson-core 2.14 or better

### ISSUE THREAD

**Issue by techwhizbang** [FasterXML/jackson-core#1210]
The time that the jackson-core library switched from using its own copy of the `fasterdoubleparser` code to the actual library this can cause JDK incompatibilities. The problem manifests itself if you take any newer version of the jackson-core libraries 2.14 or better and you need to do any type of dependency shading. If you do - the `fasterdoubleparser` uses a technique of putting all the class files across different JDK's well beyond the advertised JDK8 compatibility via the Maven assembly plugin (https://github.com/wrandelshofer/FastDoubleParser/blob/main/fastdoubleparser/src/assembly/mrjar.xml). 

When shading you end up getting all the class files for all the JDK's and if you aren't using the highest JDK version possible you will run into problems like this: 

java.lang.IllegalArgumentException: Unsupported class file major version 63
        at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)

For example I am using JDK17 and the Gradle Shadow plugin. The ASM library aborts when it finds a class file that isn't inline with the JDK you are running. 

This is easily reproducible if you use the Gradle Shadow plugin or the Maven Shade plugin and include the jackson-core 2.15.2 as a dependency for example.

**Comment by pjfanning** [comment]
Please read https://openjdk.org/jeps/238 -- MR Jars are an important feature of Java.

Please raise this with Gradle and Gradle Shadow plugin. Try upgrading to latest Gradle and Gradle plugin.

I use Gradle and it works fine with jackson-core.

**Comment by techwhizbang** [comment]
I'm tried using Gradle 7.x and Gradle 8.x. It works fine with Gradle a standard build. 

The problem arises if you attempt to use jackson-core in a shadow jar with either the Maven shade or Gradle shadow plugin. 

I suppose your point is that the shadow plugins and libraries may need to be updated to work in harmony with https://openjdk.org/jeps/238.

**Comment by GedMarc** [comment]
Not quite, The classes are compiled in JDK 19 and you are building with JDK 17.
Version 63 = JDK 19

**Comment by cowtowncoder** [comment]
I think it is unfortunate there are issues wrt shading, MR jars. But I am not quite sure what could be done here to help?

Leaving issue open so anyone with problems can find it, and maybe we get some ideas for versions of tools that help, and perhaps workarounds.

**Comment by bereng** [comment]
I ran into a similar problem and I managed to workaround it by excluding the higher jdk version compiled classes from shading.

Here is the snippet for Gradle shading plugin just before the `relocate` commands
```exclude 'META-INF/versions/17/', 'META-INF/versions/19/', 'META-INF/versions/21/'```

Here is the same for the `maven-shade-plugin` where you add these exclusions
```
<exclude>META-INF/versions/17/**</exclude>
<exclude>META-INF/versions/19/**</exclude>
<exclude>META-INF/versions/21/**</exclude>
```

**Comment by cowtowncoder** [comment]
Thank you for sharing this @bereng ! This should be very helpful for others with Gradle + Shading use case.

One quick question: was the build with JDK 11? Guessing since you are not excluding

    <exclude>META-INF/versions/11/**</exclude>

which would make sense? (but someone with Java 8 build, if any, would also need to exclude that)

**Comment by bereng** [comment]
Yes I was building with JDK11. The actual numbers in compile/shading errors and exclusion commands will vary depending on the JDK versions packed in the jar and that you are running.

This also affects any other jars and plugins where incompatible JDK combinations are hit.

**Comment by cowtowncoder** [comment]
FWTW, issue has so far been reported for Gradle-builds that use shading (as far as I know).
If anyone has seen problems with other set ups, feel free to add a note.

Similarly if the issue has been resolved with later Gradle versions, that'd be good to know: as far as we know, JDK-specific classes should work the way things are wrt Multi-Release specification.

**Comment by cowtowncoder** [comment]
Denoting that this is unlikely to be changed (by adding label) -- leaving open for visibility to users affected.
