### ISSUE TITLE
Jackson in native image failed to deserialize JsonNode into ConcurrentHashMap with generics

### ISSUE THREAD

**Issue by zipper01** [FasterXML/jackson-core#1227]
The deserializer is claimed as `@JsonDeserialize(using = Subscriber.Deserializer.class)` and defined as below, which works perfectly in a jar file running with `Java -jar`:

        public static class Deserializer extends StdDeserializer<Subscriber> {
    
            public Deserializer() {
                //super(Subscriber.class);
                this(null);
            }
    
            public Deserializer(Class<?> vc) {
                super(vc);
            }
    
            @Override
            public Subscriber deserialize(JsonParser jp, DeserializationContext ctx)
                    throws IOException, JsonProcessingException {
                JsonNode node = jp.getCodec().readTree(jp);
                if (node.isEmpty()) {
                    return null;
                }
    
                JsonNode v = node.get("statusId");
                int id = v == null ? -1 : v.asInt(-1);
                v = node.get("name");
                String name = v == null ? null : v.asText(null);
                v = node.get("password");
                String password = v == null ? null : v.asText(null);
                ConcurrentHashMap<Integer, Account> accounts = null;
                v = node.get("accounts");
                if (v != null) {
                    accounts = (new ObjectMapper()).convertValue(v,
                            new TypeReference<ConcurrentHashMap<Integer, Account>>() {
                    });
                }
                return new Subscriber(id, name, password, accounts);
            }
        }

But after I converted the jar file to a native image using GraalVM's native-image tool; it threw the below exception (at line `convertValue`) at run-time:

    java.lang.IllegalArgumentException: Cannot construct instance of `java.util.concurrent.ConcurrentHashMap` (no Creators, like default constructor, exist): no default constructor found
     at [Source: UNKNOWN; byte offset: #UNKNOWN]
            at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4618)
            at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4559)
            at myclient.sub.Subscriber$Deserializer.deserialize(Subscriber.java:71)
            at myclient.sub.Subscriber$Deserializer.deserialize(Subscriber.java:43)
            at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4613)
            at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4549)
            at myclient.AgencyMgr.onCtrlLoginSucceeded(AgencyMgr.java:345)
            at myclient.AgencyMgr.lambda$ctrlLogin$4(AgencyMgr.java:338)
            at myclient.net.MyClientEndpoint.runBlockingCtrlOperation(MyClientEndpoint.java:271)
            at myclient.AgencyMgr.ctrlLogin(AgencyMgr.java:333)
            at myclient.AgencyMgr.login(AgencyMgr.java:240)
            at myclient.ui.UIMgr.lambda$new$2(UIMgr.java:26)
            at myclient.ui.Tui$1.run(Tui.java:93)
            at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
            at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
    Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.util.concurrent.ConcurrentHashMap` (no Creators, like default constructor, exist): no default constructor found
     at [Source: UNKNOWN; byte offset: #UNKNOWN]
            at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1887)
            at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:414)
            at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1375)
            at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:439)
            at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
            at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4613)
            ... 14 more

I tried to use `MapType type = jsonObjectMapper.getTypeFactory().constructMapType(ConcurrentHashMap.class, Integer.class, Account.class)` instead of `TypeReference` and it resulted in the same.
The `jackson.core version` is 2.16.1 and:
    native-image --version
    native-image 21.0.2 2024-01-16
    GraalVM Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30)
    Substrate VM Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS, serial gc, compressed references)

I posted this to [StackOverflow](https://stackoverflow.com/questions/77989358/jackson-in-native-image-failed-to-deserialize-jsonnode-into-concurrenthashmap-wi) and got no correct answer and I realized it may need to change the Jackson Jason lib.

**Comment by cowtowncoder** [comment]
Wrong repo, will move to `jackson-databind`.
