### ISSUE TITLE
java.lang.OutOfMemoryError during deserialization

### ISSUE THREAD

**Issue by psindrome** [FasterXML/jackson-core#18]
The stacktrace has been attached at the bottom. Known issue ?

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space 
        at com.fasterxml.jackson.core.util.TextBuffer._charArray(TextBuffer.java:705)
        at com.fasterxml.jackson.core.util.TextBuffer.expand(TextBuffer.java:664)
        at com.fasterxml.jackson.core.util.TextBuffer.append(TextBuffer.java:468)
        at com.fasterxml.jackson.core.io.SegmentedStringWriter.write(SegmentedStringWriter.java:67)
        at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._flushBuffer(WriterBasedJsonGene
rator.java:1799)
        at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._writeString(WriterBasedJsonGene
rator.java:975)
        at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeString(WriterBasedJsonGener
ator.java:436)
        at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:3
6)
        at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:1
)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter
.java:464)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerB
ase.java:504)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:117)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedLi
stSerializer.java:94)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedLi
stSerializer.java:1)
        at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.serialize(AsArraySerializerB
ase.java:150)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter
.java:464)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerB
ase.java:504)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:117)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedLi
stSerializer.java:94)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedLi
stSerializer.java:1)
        at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.serialize(AsArraySerializerB
ase.java:150)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter
.java:464)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerB
ase.java:504)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:117)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedLi
stSerializer.java:94)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedLi
stSerializer.java:1)
        at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.serialize(AsArraySerializerB
ase.java:150)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter
.java:464)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerB
ase.java:504)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:117)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedLi
stSerializer.java:94)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedLi
stSerializer.java:1)

**Comment by JonasJurczok** [comment]
![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

**Comment by cowtowncoder** [comment]
lol. That is... surprisingly close hit. :)

(I lived in Denver when I chose my nick for OSS work -- alternative to "cowtown coding" was "conman consulting" so I could have become "conmanconsult" had coin flip went the other way)

**Comment by JonasJurczok** [comment]
Man, you passed on conmanconsult? I have to steal that name for the future :D

The problem I have is that the object tree is extremely strangely formed. It is basically a tree but every object has a reference to a list with all objects that are common on some dimension. This is true for all objects for multiple dimensions.

So for every object Jackson finds multiple lists with all objects of the same dimension.
This is a type of infinite recursion that it simply cannot decode.

The source file is 50kb, the serializer crashed at 70gb of output.

I just skip the whole deserialisation stuff and solve the problem differently.

Thanks for the hint, though.

**Comment by cowtowncoder** [comment]
@JonasJurczok I am not sure I understand the use case at all, but I am also curious as to how the size could explode that radically. At least with out of the box functionality. Perhaps some interesting custom (de)serializers in the mix?

**Comment by JonasJurczok** [comment]
Hey, I totally forgot to respond here apparently..

The problem turned out to be the object structure.

To illustrate picture two objects
`Obj A
- Name = A
- attributelist = L-1

Obj B
- Name = B
- attributelist = L-1

Obj L-1
- Name = Attributes
- objects = [A, B]`

So for every deserialisation of A Jackson would also serializeB and for every B it would serialize A.
But I have ~30 Objects, each containting 3-5 Lists of this kind with 15-20 objects in each list.
And that permutates to hell and back apparently.

I now solved it by not serializing it at all but instead using the debugger and some code to inspect the object. It's not perfect but better than nothing :)

**Comment by cowtowncoder** [comment]
@JonasJurczok ah. Ok that makes sense. For general purpose debugging/troubleshooting, use of `@JsonIdentityInfo` (which can solve cyclic dep problems, only fully serializing instance once) probably would not work.

**Comment by JonasJurczok** [comment]
Yeah, it doesn’t :D
