### ISSUE TITLE
Mapping error when expected parse error

### ISSUE THREAD

**Issue by dminkovsky** [FasterXML/jackson-core#203]
I am guessing that the following is attributable to a lack of understanding on my part, but:

- Parsing: `{ "id": "hello }`
- Expected: `JsonParseException`
- Got: `JsonMappingException: "Unexpected end-of-input in VALUE_STRING"`

Why would this be a mapping error, considering that my JSON is not parseable/valid? Or, is it?

**Comment by cowtowncoder** [comment]
It should be `JsonParseException`, but sounds like something is catching that (`JsonParser` will throw is at `JsonParseException`) and re-throwing it as `JsonMappingException`. Do you have a stack trace that could indicate where this occurs?

**Comment by dminkovsky** [comment]
I had  a trace already and looks like I didn't look at it carefully enough: it is, indeed, caused by a `JsonParseException`. I am using the JAX-RS provider. Do you know why it would be getting wrapped by the `JsonMappingException`?

Here is the trace:
```
com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input in VALUE[18/1891]
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@81daecf; line: 1, column: 33] (through reference chain: motif.web.resource.Put
User["id"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
        at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.wrapAndThrow(BeanPropertyMap.java:439)
        at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
        at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1410)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:860)
        at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:808)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:260)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:236)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:74)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:853)
        at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:270)
        at org.glassfish.jersey.server.internal.inject.EntityParamValueFactoryProvider$EntityValueFactory.provide(EntityParamValueFactoryProvider.java:96)
        at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:81)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:127)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:143)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:375)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input in VALUE_STRING
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@81daecf; line: 1, column: 33]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:455)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:451)
        at com.fasterxml.jackson.core.base.ParserBase.loadMoreGuaranteed(ParserBase.java:460)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2306)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString(UTF8StreamJsonParser.java:2287)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:286)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseLong(StdDeserializer.java:444)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:321)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:303)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
        at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
        ... 35 more
```

**Comment by dminkovsky** [comment]
Closed here: should I open in the JAX-RS provider repo?

**Comment by dminkovsky** [comment]
A bit more flavor:

When I change the JSON string to `{ "id", "hello" }`, I do get a `JsonParseException`. The difference in stack traces is that in the case above `BeanDeserializer.deserialize()` invokes `BeanDeserializer.vanillaDeserialize()`, but in the case here, `BeanDeserializer.deserialize()` invokes `UTF8StreamJsonParser.nextToken()`.

The trace:

```  
      at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:704)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
        at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1410)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:860)
        at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:808)
```

**Comment by cowtowncoder** [comment]
Ah. Hmmh.

This is trickier, because there is a valid reason for doing this -- only `JsonMappingException` can contain information on position within Object hierarchy, plain `JsonParsingException` (or generally `JsonProcessingException`) does not.
Then again, discrepancy between the cases is not optimal.

I think there have been some very recent fixes in this area, to make sure all code paths lead to same handling, which in this case means wrapping.

One thing you may use, if you do want to reduce wrapping, is to disable:

* `DeserializationFeature.WRAP_EXPECTIONS`
* `SerializationFeature.WRAP_EXPECTIONS`

as these should control whether this wrapping occurs or not.

**Comment by dminkovsky** [comment]
Thanks for the work-around! That should help. My approach before your reply was to check `getCause()` and take it from there if necessary.

Should I open this elsewhere? Re-open it here?

Thank you for your help and for Jackson.

**Comment by cowtowncoder** [comment]
@dminkovsky I think this does belong under `jackson-databind`. And since it does look like handling is inconsistent, yes, please re-file there, with stack trace. It looks like even with latest 2.6.0-rc3, there is some room for improvement.

**Comment by kewpiedoll99** [comment]
in `{ "id": "hello }` you aren't closing your "hello" string

**Comment by dminkovsky** [comment]
Yes, I was expecting an error.
