### ISSUE TITLE
TypeReference does not enforce presence of type argument at compile time

### ISSUE THREAD

**Issue by wheleph** [FasterXML/jackson-core#210]
According to comments in source code one should not be able to create subclass of `TypeReference` without type argument due to Java compiler error:

```java
    protected TypeReference()
    {
        Type superClass = getClass().getGenericSuperclass();
        if (superClass instanceof Class<?>) { // sanity check, should never happen
            throw new IllegalArgumentException("Internal error: TypeReference constructed without actual type information");
        }
        /* 22-Dec-2008, tatu: Not sure if this case is safe -- I suspect
         *   it is possible to make it fail?
         *   But let's deal with specific
         *   case when we know an actual use case, and thereby suitable
         *   workarounds for valid case(s) and/or error to throw
         *   on invalid one(s).
         */
        _type = ((ParameterizedType) superClass).getActualTypeArguments()[0];
    }

// More code here...

    /**
     * The only reason we define this method (and require implementation
     * of <code>Comparable</code>) is to prevent constructing a
     * reference without type information.
     */
    @Override
    public int compareTo(TypeReference<T> o) { return 0; }
```

However the simple class below compiles without errors by javac 1.8 and javac 1.6:

```java
import com.fasterxml.jackson.core.type.TypeReference;

public class JacksonTest {
    public static void main(String[] args) {
        TypeReference typeReference = new TypeReference() {};
        System.out.println(typeReference.getType());
    }
}
```

Of course if I launch the test it's going to fail at runtime (at the line with comment `// sanity check, should never happen`):
```
Exception in thread "main" java.lang.IllegalArgumentException: Internal error: TypeReference constructed without actual type information
	at com.fasterxml.jackson.core.type.TypeReference.<init>(TypeReference.java:35)
	at JacksonTest$1.<init>(JacksonTest.java:5)
	at JacksonTest.main(JacksonTest.java:5)
```

So it's seems like implementing `Comparable` by `TypeReference` does not give any benefits and. Does it?

**Comment by cowtowncoder** [comment]
Original article suggested it should, but perhaps it does not. I am open to improvement ideas; it would be great if there was a way to avoid this problem. However, given that type information is all around optional for backwards compatibility, perhaps there is no way to achieve that.

**Comment by wheleph** [comment]
I also don't see a way to have compile-time guarantees that the argument is present. I would suggest getting rid of implementing `Comparable` to make the code shorter and easier.

**Comment by cowtowncoder** [comment]
@wheleph I am not against that, but I want to have a look at the original article to see why I thought this would help. Perhaps use case here differs from the original.

**Comment by wheleph** [comment]
@cowtowncoder here's the original article: http://gafter.blogspot.com/2006/12/super-type-tokens.html. I think the use case described there is completely analogous to Jackson's type reference. I tried to get in touch with the author of the comment that proposed to implement `Comparable` but didn't receive any answer yet. You know, it was 8 years ago...

**Comment by cowtowncoder** [comment]
Yes, I understand that it was a while ago, but Java the language hasn't really changed much, so in all likelihood the approach makes as much sense now than it did then. But how much is that... :)
