### ISSUE TITLE
parsing failing if file path is the json value

### ISSUE THREAD

**Issue by sreev** [FasterXML/jackson-core#264]
jackson version: 2.6.4

file: test.json

```json
[{
"name": "my application",
"folder": "/usr/lib/myApp"
}]
```

code:

```java
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.configure(ALLOW_COMMENTS, TRUE); // tried other Features and combination, too.
JsonNode jsonNode = objectMapper.readTree("test.json");
System.out.println(jsonNode.asText());
```

**Comment by cowtowncoder** [comment]
Failing how?

**Comment by sreev** [comment]
Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Unexpected character ('U' (code 85)): was expecting either '*' or '/' for a comment
 at [Source: test.json; line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:462)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComment(ReaderBasedJsonParser.java:2111)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd2(ReaderBasedJsonParser.java:2074)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2025)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:577)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3776)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2271)

**Comment by cowtowncoder** [comment]
Uh. Ok, I'll give a hint as to the nature of problem here.... have a look at signature of `readTree(String)` method. :-)

**Comment by sreev** [comment]
Come on, 'readTree' is overloaded, it also takes File and total 7 input types including String.

Please re-open.

    private void _skipComment() throws IOException
    {
        if (!isEnabled(Feature.ALLOW_COMMENTS)) {
            _reportUnexpectedChar('/', "maybe a (non-standard) comment? (not recognized as one since Feature 'ALLOW_COMMENTS' not enabled for parser)");
        }
        // First: check which comment (if either) it is:
        if (_inputPtr >= _inputEnd && !loadMore()) {
            _reportInvalidEOF(" in a comment");
        }
        char c = _inputBuffer[_inputPtr++];
        if (c == '/') {
            _skipLine();
        } else if (c == '*') {
            _skipCComment();
        } else { ///////////////////////////////////// this is where the issue is. after every backslash, it expects either / or * otherwise, it throws exception
            _reportUnexpectedChar(c, "was expecting either '*' or '/' for a comment");
        }
    }

**Comment by cowtowncoder** [comment]
@sreev I don't usually say this but... what the fuck?

I pointed to you to the BUG IN YOUR CODE that causes fail here. And you ask for re-open without DOING ANYTHING but asking ME to fix YOUR bug? Seriously?
Thye method you include has absolutely NOTHING to do with the problem. Do read the Exception, have a look at `readTree(String)` method. It is kind of obvious when you look at MEANING of String argument.

**Comment by sreev** [comment]
@cowtowncoder, Further from my e-mail. I am sorry, Tatu. I was reading the "string name of file" as 'File' object, argument for overloaded readTree() method.

**Comment by cowtowncoder** [comment]
@sreev ok. Glad you were able to find description of the intended argument type. Apologies for earlier rant.
