### ISSUE TITLE
Inconsistent overload behavior when parsing numerical unquoted JSON key

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-core#273]
(moved from https://github.com/FasterXML/jackson-databind/issues/1205)

------

The following statement

```java
new ObjectMapper()
	.configure(JsonParser.Feature.ALLOW_UNQUOTED_FIELD_NAMES, true)
	.readTree("{0:0}");
```

throws an exception with the following stack trace:

```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('0' (code 48)): was expecting either valid name character (for unquoted name) or double-quote (for quoted) to start field name
 at [Source: java.io.StringReader@550de6b8; line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1369)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:532)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:453)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleUnusualFieldName(ReaderBasedJsonParser.java:1281)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseFieldName(ReaderBasedJsonParser.java:1162)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:602)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:197)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:59)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1750)
```

Yet when using the `byte[]` overload it works just fine:

```java
new ObjectMapper()
	.configure(JsonParser.Feature.ALLOW_UNQUOTED_FIELD_NAMES, true)
	.readTree("{0:0}".getBytes("UTF-8"))
```

I'm using version 2.2.3.

**Comment by cowtowncoder** [comment]
Can not reproduce with 2.7.3: both input types actually allow "names" that start with a digit.
