### ISSUE TITLE
object to json JsonMappingException

### ISSUE THREAD

**Issue by 34gl3** [FasterXML/jackson-core#298]
I'm new to jackson project. I want to convert an htmlpage object(Htmlunit) to json but it throws a JsonMappingException caused by an exception in htmlunit. how do make it work?
```

com.fasterxml.jackson.databind.JsonMappingException: HtmlPage.getImplementation is not yet implemented.
HtmlPage.getImplementation is not yet implemented.
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:303)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3672)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2988)
	at test.htmlunit.getPage(htmlunit.java:83)
	at test.main.main(main.java:25)
Caused by: java.lang.UnsupportedOperationException: HtmlPage.getImplementation is not yet implemented.
	at com.gargoylesoftware.htmlunit.html.HtmlPage.getImplementation(HtmlPage.java:530)
	at org.apache.xml.serializer.dom3.LSSerializerImpl.getXMLVersion(LSSerializerImpl.java:1383)
	at org.apache.xml.serializer.dom3.LSSerializerImpl.writeToString(LSSerializerImpl.java:1123)
	at com.fasterxml.jackson.databind.ext.DOMSerializer.serialize(DOMSerializer.java:40)
	at com.fasterxml.jackson.databind.ext.DOMSerializer.serialize(DOMSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
	... 6 more
```

**Comment by cowtowncoder** [comment]
First of all: usage questions are best asked on:

https://groups.google.com/forum/#!search/jackson-users

as this is quite literally why we have the group.

But as to exception; it seems to come from:

    at com.gargoylesoftware.htmlunit.html.HtmlPage.getImplementation(HtmlPage.java:530)

so HtmlUnit does not like `getImplementation()` getting called.

Since Jackson has no idea of what type like `HtmlPage` is, other than by what getters and setters it exposes, it calls all getters. In this case it is likely that a custom serializer would be needed to either use different strategy, or block attempts at serializing logical property `implementation`.

**Comment by 34gl3** [comment]
Thank you for your response, I will ask my questions on google group next time.
Is there any workaround to this problem in Jakson? for example escape the getimplementation by jakson?
I don't want to modify htmlunit and remove getimplementation from source.

**Comment by cowtowncoder** [comment]
@34gl3 you may want to check out "mix-in annotations", that could work.
