### ISSUE TITLE
Signature change in GeneratorBase.getOutputContext() breaks binary compatibilty

### ISSUE THREAD

**Issue by olivergierke** [FasterXML/jackson-core#313]
Code that has been compiled against Jackson versions < 2.8 using `GeneratorBase.getOutputContext()` will fail on 2.8 as the method signature has changed. Example here: current Elasticsearch (2.3.3) compiling against 2.6.6. Failing with this exception on 2.8.1:

```
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.base.GeneratorBase.getOutputContext()Lcom/fasterxml/jackson/core/json/JsonWriteContext;
    at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeEndRaw(JsonXContentGenerator.java:327)
    at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeRawField(JsonXContentGenerator.java:351)
    at org.elasticsearch.common.xcontent.XContentBuilder.rawField(XContentBuilder.java:909)
```

**Comment by cowtowncoder** [comment]
Yes, this is an unfortunate finding, and something I don't know what we could do anything about at this point. While change is source compatible, it is not binary compatible; and worse, I don't think there is a way to introduce hidden/synthetic method for backwards compatibility. Change itself is needed as the original signature incorrectly specified too specific return type, and would not allow sub-classing of `JsonStreamContext`

**Comment by cowtowncoder** [comment]
Not sure what else could be done: as I said this is unfortunate, but I don't think there is much to be done it having been done and released.
