### ISSUE TITLE
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token  at [Source: {"phoneNo":"15988909098","password":"xxx"}; line: 1, column: 1] 

### ISSUE THREAD

**Issue by sdcuike** [FasterXML/jackson-core#345]
when I used this way:

         ObjectMapper objectMapper = new ObjectMapper();
        String content = "{\"phoneNo\":\"xxx\",\"password\":\"xxx\"}";
        JavaType valueType = objectMapper.constructType(String.class);
        Object readValue = objectMapper.readValue(content, valueType);

that is a jsonString(content) convert to String ([simple type, class java.lang.String]), not support：

Exception occurred:
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: {"phoneNo":"xx","password":"xx"}; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:60)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2880)
	at com.doctor.commons.mail.xxTest.main(xxx.java:13)

**Comment by cowtowncoder** [comment]
Yes. JSON Object is not a String. What exactly is your expectation here?

**Comment by sdcuike** [comment]
write only a test ，Thank you for your answer.

**Comment by Errr0rr404** [comment]
what was the solution to this issue ??

**Comment by cowtowncoder** [comment]
@Errr0rr404 fix the code: you can not read a `String` out of JSON Object.

**Comment by mluis** [comment]
I'm facing this issue. And I want it to remain a String besides it seems a json object.

I've created class Data with:
@JsonProperty("data")
	private String data;

How do you overcome this?
