### ISSUE TITLE
XMLStreamWriter "Trying to output second root"

### ISSUE THREAD

**Issue by giulio-quaresima** [FasterXML/jackson-core#352]
I'm used to use `javax.xml.stream.XMLStreamWriter` to generate simple XMLs and XML **fragments**. 
I have Jackson in the classpath: starting from version 2.8, when I try to generate an XML fragment, I'm facing a new error:
```
Exception in thread "main" javax.xml.stream.XMLStreamException: Trying to output second root, <foo>
	at com.ctc.wstx.sw.BaseStreamWriter.throwOutputError(BaseStreamWriter.java:1564)
	at com.ctc.wstx.sw.BaseStreamWriter.throwOutputError(BaseStreamWriter.java:1571)
	at com.ctc.wstx.sw.BaseStreamWriter.reportNwfStructure(BaseStreamWriter.java:1599)
	at com.ctc.wstx.sw.BaseNsStreamWriter.checkStartElement(BaseNsStreamWriter.java:469)
	at com.ctc.wstx.sw.BaseNsStreamWriter.writeStartElement(BaseNsStreamWriter.java:290)
	at it.unipg.bugs.jackson.XmlStreamWriterBug.main(XmlStreamWriterBug.java:18)
```
You can reproduce this error with the following code and jackson-core >= 2.8.0:
```
import javax.xml.stream.FactoryConfigurationError;
import javax.xml.stream.XMLOutputFactory;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamWriter;

public class XmlStreamWriterBug
{
	public static void main(String[] args) throws XMLStreamException, FactoryConfigurationError
	{
		XMLStreamWriter xmlWriter = XMLOutputFactory.newInstance().createXMLStreamWriter(System.out);
		xmlWriter.writeStartDocument();
		xmlWriter.writeStartElement("bar");
		xmlWriter.writeEndElement();
		xmlWriter.writeStartElement("foo"); // Exception with jackson >= 2.8.0 (woodstox-core 5.x)
		xmlWriter.writeEndElement();
		xmlWriter.writeEndDocument();
		xmlWriter.flush();
	}
}
```
This seems caused by the new dependency to woodstox 5.x, which acts as a provider for `javax.xml.stream.XMLOutputFactory`

If `javax.xml.stream.XMLStreamWriter` was intended to produce whole XML documents only, this behaviour would be right, but it is not stated by the default documentation. After all, also with >= 2.8.0, you can omit to call `xmlWriter.writeStartDocument()` and you obtain an XML fragment without error:
```
XMLStreamWriter xmlWriter = XMLOutputFactory.newInstance().createXMLStreamWriter(System.out);
xmlWriter.writeStartElement("bar");
xmlWriter.writeCharacters("Bye");
xmlWriter.writeEndElement();
```
XML output:
```
<bar>Bye</bar>
```
but you can't call `xmlWriter.writeStartElement("foo")` again, obtaining the exception. Why?

**Comment by uhhhh2** [comment]
Should this go in https://github.com/FasterXML/jackson-dataformat-xml ?

**Comment by cowtowncoder** [comment]
Yes.

**Comment by cowtowncoder** [comment]
May be re-filed at `jackson-dataformat-xml`.
