### ISSUE TITLE
@JsonTypeInfo not working when annotating a type's polymorphic field and a PropertyNamingStrategy is in use

### ISSUE THREAD

**Issue by futuretelematics** [FasterXML/jackson-core#393]
(a test-case that reproduces the issue is attached)
[PolymorphicTest.zip](https://github.com/FasterXML/jackson-core/files/1197853/PolymorphicTest.zip)

If the following conditions are met:
(1) a type's polymorphic field is annotated with `@JsonTypeInfo`
```java
	public static class DogAndCat {
		@JsonTypeInfo(include = JsonTypeInfo.As.PROPERTY,
					  use = JsonTypeInfo.Id.NAME,
					  property = "type")
		@Getter @Setter private Animal _dog;		
		@Getter @Setter private Cat _cat;
	}
```
(2) a `PropertyNamingStrategy` is in use
```java
ObjectMapper jsonMapper = new ObjectMapper();	
jsonMapper.setPropertyNamingStrategy(PropertyNamingStrategy.CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES);
```

Then the serialization works:
```
{"dog":{"type":"dog","name":"bruce"},"cat":{"name":"patty"}}
```
BUT the de-serialization fails: 
```json
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `r01f.test.types.PolymorphicTest$Animal` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (String)"{"dog":{"type":"dog","name":"bruce"},"cat":{"name":"patty"}}"; line: 1, column: 8] (through reference chain: r01f.test.types.PolymorphicTest$DogAndCat["dog"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1438)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1027)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:265)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:519)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:416)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1265)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:325)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
	at r01f.test.types.PolymorphicTest.main(PolymorphicTest.java:104)
```

**Comment by cowtowncoder** [comment]
Could you please include code you are using for deserialization? That mayb be relevant wrt failure.

Also, are you using additional libs/frameworks in this case? Like Lombok maybe? (asking because of annotations included in sample).

**Comment by futuretelematics** [comment]
While **removing lombok** from the test case I found that **everything works**; so I guess the problem is related with lombok's `@NoArgsConstructor` 
I'll do a little research about this

(attached goes a zip file with the test cases) 
[LombokPolimorphicTest.zip](https://github.com/FasterXML/jackson-core/files/1207185/LombokPolimorphicTest.zip)

Thank you very much!!

**Comment by futuretelematics** [comment]
OK!!
Just adding: 		`jsonMapper.configure(MapperFeature.INFER_CREATOR_FROM_CONSTRUCTOR_PROPERTIES,false);` solves the issue

Maybe it's related with https://github.com/FasterXML/jackson-databind/issues/1197

Thanks a lot!!
