### ISSUE TITLE
Breaking API change introduced in Jackson 2.9.0

### ISSUE THREAD

**Issue by elandau** [FasterXML/jackson-core#395]
An API change introduced in Jackson version 2.9.0 is breaking several open source projects, such as Swagger.  Would it be possible to go through a deprecation cycle instead of changing a public API so other projects have time to update to the new API?

Here is an example stack trace of the breaking change in Swagger's 
[https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java](ModelResolver.java)

```
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.annotations()Ljava/lang/Iterable;
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:379)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:185)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:100)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:236)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:185)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:100)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:161)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:112)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:80)
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:896)
	at io.swagger.jaxrs.Reader.read(Reader.java:322)
	at io.swagger.jaxrs.Reader.read(Reader.java:172)
```

**Comment by cowtowncoder** [comment]
This would belong under `jackson-databind`; this repository is for low-level streaming API.
