### ISSUE TITLE
NullPointerException in CharsToNameCanonicalizer.findSymbol

### ISSUE THREAD

**Issue by ptaillard** [FasterXML/jackson-core#401]
Hello,

We found a regression on Jackson core library. We catch a NPE on CharsToNameCanonicalizer.findSymbol(CharsToNameCanonicalizer.java:437)
This issue appears since the version 2.8.7 (2.8.6 and before is fine).

Here the source code to reproduce the issue.
1/ Define the DoubleDeserializer class:

```
public class DoubleDeserializer extends JsonDeserializer {
    @Override
    public Object deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
        JsonNode node = p.getCodec().readTree(p);
        String json = node.textValue();

        Reader reader = new StringReader(json);
        IOContext context = new IOContext(new BufferRecycler(), reader, true);
        JsonParser internalParser = new ReaderBasedJsonParser(
                context,
                p.getFeatureMask(),
                reader,
                p.getCodec(),
                CharsToNameCanonicalizer.createRoot()
        );
        final Class clazz;
        try {
            clazz = p.getCurrentValue().getClass().getDeclaredField(p.getCurrentName()).getType();
        } catch (NoSuchFieldException e) {
            //This may happen as we're not doing a recursive search for the field.
            throw new JsonParseException(p, "Can't find field "+p.getCurrentName()+" in "+p.getCurrentValue(), e);
        }
        return p.getCodec().readValue(internalParser, clazz);
    }
}
```

Then create the corresponding test:
```
public class DoubleDeserializerTest {

    private static class Bean {
        public String foo;
    }

    private static class BeanContainer {
        @JsonDeserialize(using = DoubleDeserializer.class)
        public Bean bean;
    }

    @Test
    public void testDeserialize() throws Exception {
        BeanContainer actual = new ObjectMapper().readValue("{\"bean\":\"{\\\"foo\\\":\\\"bar\\\"}\"}", BeanContainer.class);
        assertNotNull(actual);
        assertNotNull(actual.bean);
        assertEquals(actual.bean.foo, "bar");
    }

}
```

And the stacktrace after running the test:
```
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.tmn.adserver.dto.rtb.openrtb.nativ.DoubleDeserializerTest$BeanContainer["bean"])

	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1607)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:278)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
	at com.tmn.adserver.dto.rtb.openrtb.nativ.DoubleDeserializerTest.testDeserialize(DoubleDeserializerTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
Caused by: java.lang.NullPointerException
	at com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer.findSymbol(CharsToNameCanonicalizer.java:437)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseName(ReaderBasedJsonParser.java:1691)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:684)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3770)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2099)
	at com.tmn.adserver.dto.rtb.openrtb.nativ.DoubleDeserializer.deserialize(DoubleDeserializer.java:44)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	... 27 more
```

**Comment by cowtowncoder** [comment]
Ok, just so you know, direct construction of `ReaderBasedJsonParser` is not supported functionality. Instances need to be created via `JsonFactory`.

The actual bug in the code is that it tries to use symbol table gotten with:

    CharsToNameCanonicalizer.createRoot()

which should never be used as is, but only as sort of factory; method you need is `makeChild()` off the root instance.

But in the end I would strongly recommend you change code to use `JsonFactory`.
There are at least 2 paths to do so:

1. `codec` has `getFactory()` method to get `JsonFactory`; call `createParser()` on it, passing String value
2. `codec` can be safely cast as `ObjectMapper` (it will always be that), and you can call `readValue()` directly passing 

(and there's probably 3rd going via `DeserializationContext` but one of above should work)

and those would simplify code and avoid construction of internal helper classes.

Hope this helps.

**Comment by ptaillard** [comment]
Many thanks for your answer @cowtowncoder !
