### ISSUE TITLE
java.util.concurrent.ExecutionException: com.fasterxml.jackson.core.JsonParseException

### ISSUE THREAD

**Issue by maotan** [FasterXML/jackson-core#474]
version: 2.5.0

java.util.concurrent.ExecutionException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Deferred': was expecting ('true', 'false' or 'null')

	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1486) ~[jackson-core-2.5.0.jar!/:2.5.0]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518) ~[jackson-core-2.5.0.jar!/:2.5.0]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3324) ~[jackson-core-2.5.0.jar!/:2.5.0]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2483) ~[jackson-core-2.5.0.jar!/:2.5.0]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:801) ~[jackson-core-2.5.0.jar!/:2.5.0]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:697) ~[jackson-core-2.5.0.jar!/:2.5.0]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3600) ~[jackson-databind-2.5.0.jar!/:2.5.0]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3545) ~[jackson-databind-2.5.0.jar!/:2.5.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2157) ~[jackson-databind-2.5.0.jar!/:2.5.0]
	at me.eleme.goc.robot.common.utils.HTTPClient.lambda$get$1(HTTPClient.java:289) ~[robot-common-1.0-SNAPSHOT.jar!/:1.0-SNAPSHOT]
	at me.eleme.goc.robot.common.utils.HTTPClient$$Lambda$8/468770203.apply(Unknown Source) ~[na:na]
	at me.eleme.goc.robot.common.utils.HTTPClient.request(HTTPClient.java:200) ~[robot-common-1.0-SNAPSHOT.jar!/:1.0-SNAPSHOT]
	at me.eleme.goc.robot.common.utils.HTTPClient.get(HTTPClient.java:290) ~[robot-common-1.0-SNAPSHOT.jar!/:1.0-SNAPSHOT]

**Comment by maotan** [comment]
happend in this code
(response -> mapper.readTree(response.body().bytes()))  ;

when http-request not frequently , the url request and response have no problem, but when request frequently  the  exception happend

**Comment by maotan** [comment]
public JsonNode get(String url, Map<String, String> params, Map<String, String> headers) throws ExecutionException, InterruptedException {
        Request.Builder builder = buildRequest(url, params, headers);
        CheckedFunction<Response, JsonNode> callback = (response -> mapper.readTree(response.body().bytes()));
        CompletableFuture<JsonNode> future = request(builder.get().build(), callback);
        return future.get();
    }

**Comment by maotan** [comment]
public <T> CompletableFuture<T> request(Request req, CheckedFunction<Response, T> function) {
        Response response = null;
        CompletableFuture<T> future = new CompletableFuture<>();
        try {
            response = client.newCall(req).execute();
            if (response.isSuccessful()) {
                logger.info("http request {}: {}, success ", req.method(), req.url().toString());
                try {
                    T t = function.apply(response);
                    future.complete(t);
                } catch (Exception e) {
                    future.completeExceptionally(e);
                }
            } else {
                logger.info("http request {}: {}, code: {}, message: {}", req.method(), req.url().toString(), response.code(), response.message());
                logger.info("Request-Body: {}", req.headers());
                String eMessage = String.format("[httpStatus: %d] %s", response.code(), response.message());
                try {
                    JsonNode jNode = mapper.readTree(response.body().bytes());
                    String httpMsg = jNode.get("message").toString();
                    eMessage = String.format("[httpStatus: %d] %s", response.code(), httpMsg);
                } catch (Exception ignore){
                }
                future.completeExceptionally(new HTTPException(response.code(), eMessage));
            }
        } catch (Exception e) {
            logger.info("http request {}: {}, exception: {}", req.method(), req.url().toString(), e.getMessage());
            future.completeExceptionally(e);
        } finally {
            if (response != null) {
                response.body().close();
            }
        }
        return future;
    }

**Comment by maotan** [comment]
I think  I  had found the reason。 

When request frequently,  Response.body.byte()  can not read the data in time, some time Response.body.byte() can not get the whole http result data, and the jsonParser exception。 the "Deferred"  in the exception message explained this

**Comment by maotan** [comment]
I tested and found that  response.body().bytes() can not get entire data some time 。 but when I use code below to detect  response.body().bytes()， and now the problem not occured。 If  not use if to detect， the problem occured again

byte[] aa = response.body().bytes();
if (aa == null || aa.length == 0) {
           logger.info("111111111");
  }

**Comment by maotan** [comment]
I found  it is the okhttp3 problem

**Comment by cowtowncoder** [comment]
@maotan Thank you for follow up, glad you found the root cause.
