### ISSUE TITLE
Deserialize error when code run on a thread

### ISSUE THREAD

**Issue by zsigui** [FasterXML/jackson-core#482]
Hello, I got this problem when I execute the code on the main thread. Could somebody help?

```
 public static void main(String[] args) {
       new Thread(new Runnable() {
            @Override
            public void run() {
                ArrayList<String> a = JsonUtil.jsonToObj("[\"a\",\"b\", \"c\"]", new ArrayList<String>(){}.getClass());
                SLogUtil.v(a);
            }
        }).start();
}
```
fine.

```
 public static void main(String[] args) {
        ArrayList<String> a = JsonUtil.jsonToObj("[\"a\",\"b\", \"c\"]", new ArrayList<String>(){}.getClass());
        SLogUtil.v(a);
}
```
error above.

The stack info as below:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `sg.jackiez.worker.app.Main$1$1` (no Creators, like default construct, exist): no default no-arguments constructor found
 at [Source: (String)"["a","b", "c"]"; line: 1, column: 1]
at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1451)
at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1027)
at com.fasterxml.jackson.databind.deser.ValueInstantiator.createUsingDefault(ValueInstantiator.java:189)
at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:267)
```

**Comment by cowtowncoder** [comment]
Just one note: construct

```java
new ArrayList<String>(){}.getClass()
```

does work around Type Erasure to include generic type BUT has the problem that it is a **non-static** inner class -- one that requires implicit `this` argument (surrounding class). Such types can not be used with Jackson, in general.
So this is why your attempt failed.
