### ISSUE TITLE
Errors while running Junit test with Jackson Core 2.9.8 with Spring 5.1.x

### ISSUE THREAD

**Issue by Prazhant** [FasterXML/jackson-core#511]
1. I am using Spring Boot 2.1.2, Spring 5.1.3 and Jackson Core 2.9.8. While running Junit test case I am getting initialization error as com.fasterxml.jackson.core.Versioned. When I downgrade version of Jackson Core to 2.9.7, it works fine. 
Stack Trace: -
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/Versioned
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
.
.
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.Versioned
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

2. For Spring Boot 2.1.2, Spring Version 5.1.4(latest release), and any version of Jackson Core from 2.8.x and above, while running Junit test case I am getting FatalBeanException during instantiation of RestTemplate.
Stack Trace:- 
java.lang.NoClassDefFoundError: org/springframework/beans/FatalBeanException
	at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.<init>(MappingJackson2HttpMessageConverter.java:59)
	at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.<init>(AllEncompassingFormHttpMessageConverter.java:76)
	at org.springframework.web.client.RestTemplate.<init>(RestTemplate.java:148)

Caused by: java.lang.ClassNotFoundException: org.springframework.beans.FatalBeanException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more

**Comment by cowtowncoder** [comment]
I don't know what could cause problems indicated above. `jackson-core` version `2.9.8` does contained `Versioned` as expected (same as every 2.x version, it has been there since early 1.x).
`FatalBeanException` is presumably something Spring provides to encapsulate a problem, so it'd make sense to see what is inside. Jackson has no knowledge of that type (it does not depend on any Spring class from core components).

You might have better chance to get help from Spring Boot folks, or possible on Jackson mailing lists.

**Comment by cowtowncoder** [comment]
Can not reproduce with given information.
