### ISSUE TITLE
NoSuchMethodError: com.fasterxml.jackson.core.JsonStreamContext

### ISSUE THREAD

**Issue by raj206** [FasterXML/jackson-core#525]
I'm trying to bump the jackson version number from 2.8.6 to 2.9.8 and it is just not working the way it is supposed to work.

It's giving this error:
```
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonStreamContext.<init>(II)V

    at com.fasterxml.jackson.databind.util.TokenBufferReadContext.<init>(TokenBufferReadContext.java:59)
    at com.fasterxml.jackson.databind.util.TokenBufferReadContext.createRootContext(TokenBufferReadContext.java:89)
    at com.fasterxml.jackson.databind.util.TokenBuffer$Parser.<init>(TokenBuffer.java:1298)
    at com.fasterxml.jackson.databind.util.TokenBuffer.asParser(TokenBuffer.java:276)
    at com.fasterxml.jackson.databind.util.TokenBuffer.asParser(TokenBuffer.java:242)
    at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2798)
    at com.example.FooTest.testFilter(FooTest.java:34)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
Don't know why `com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2798)` is  throwing the error. Did the implementation change?

**Comment by cowtowncoder** [comment]
@raj206 You seem to be running different (incompatible) versions of `jackson-core` and `jackson-databind`. Ideally minor versions should be the same, but minor version of `jackson-core` MUST be at least that of `jackson-databind`.

So: make sure `jackson-core` also has version `2.9.8` (as well as `jackson-annotations`).
Otherwise method that `jackson-databind` 2.9 has been complied against is not present in implementation.

**Comment by raj206** [comment]
Thank you so much! I had to put about 15 `<exclusion>`s but it works now!

**Comment by cowtowncoder** [comment]
@raj206 glad you managed to resolve it. Usually it's easiest to add explicit dependency to `jackson-core`, if one was missing OR get managed versions using `jackson-bom` (which is pom that contains full version set of all compatible Jackson versions -- so, `jackson-bom` `2.9.8` would have `2.9.8` of databind, core etc -- not as dependencies, but as managed dependency versions so you will only include dependencies to components you need, but leave version out of individual dependency.
