### ISSUE TITLE
Can't deserialize int to double through constructor

### ISSUE THREAD

**Issue by reda-alaoui** [FasterXML/jackson-core#532]
I am using Jackson 2.9.7.

Considering the following classes:

```java
public static class Foo {
    private Bar bar;

    public Bar getBar() {
      return bar;
    }

    public void setBar(Bar bar) {
      this.bar = bar;
    }
  }

public class Bar {
  private final double value;

  public Bar(double value) {
    this.value = value;
  }

  @JsonValue
  public double value() {
    return value;
  }
}
```

`objectMapper.readValue("{\"bar\": 1}", Foo.class);` fails while `objectMapper.readValue("{\"bar\": 1.0}", Foo.class)` succeeds.

If `Foo.bar` is turned into a `double`, both succeed.

The failure stacktrace:

```java
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `DoubleDeserializationTest$Bar` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (1)
 at [Source: (String)"{"bar": 1}"; line: 1, column: 9] (through reference chain: DoubleDeserializationTest$Foo["bar"])

	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1032)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromInt(ValueInstantiator.java:262)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromInt(StdValueInstantiator.java:356)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromNumber(BeanDeserializerBase.java:1324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:173)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
```

I think it is a bug

**Comment by cowtowncoder** [comment]
No, that works as expected: exception message indicates the nature of the problem. You need to add a `int`-valued (or `long`, `Long` or `Integer`) valued creator method.

**Comment by davidmoten** [comment]
I think this should be reopened because the suggested fix isn't practical. 

Suppose I have three or even more double values in the constructor:

`public Bar(double value1, double value2, double value3) `

Looking at your suggestion we need to add these constructors just to add coverage of int and double:

```
public Bar(int value1, double value2, double value3) 
public Bar(double value1, int value2, double value3) 
public Bar(double value1, double value2, int value3) 
public Bar(int value1, int value2, double value3) 
public Bar(int value1, double value2, int value3) 
public Bar(double value1, int value2, int value3) 
public Bar(int value1, int value2, int value3) 
```

In fact if I have n double parameters in the constructor I need 3^n constructors to cover all the combinations of int, long, double!

**Comment by cowtowncoder** [comment]
@davidmoten That is actually different use case since 1-argument Constructors are... tricky. There's both "delegating" and "properties" based approach available (that is, from JSON number (delegating) OR from JSON Object with just 1 property): in your case only "properties" one is possible (must come from JSON Object, not JSON Number).
Because of this, your case likely already works (which is inconsistent, I know; but code path is different).

If not, feel free to file at `jackson-databind` (this is wrong repo as it's only about lower-level streaming parser/generator).

Original request may also be re-filed at `jackson-databind` if anyone feels that 1-arg delegation based Creator case should be supported. It has its own challenges but I am not necessarily against change like this, at this point in time.
