### ISSUE TITLE
java.io.IOException: Expected END_ELEMENT, got event of type 1

### ISSUE THREAD

**Issue by hasanbirol89** [FasterXML/jackson-core#543]
When i use xmlMapper.readTree , FasterXML gets an error. (java.io.IOException: Expected END_ELEMENT, got event of type 1)
<EXCEPTION>
<![CDATA[
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at 
]]>
</EXCEPTION>

**Comment by hasanbirol89** [comment]
<EXCEPTION>
<![CDATA[
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
]]>
</EXCEPTION>

**Comment by hasanbirol89** [comment]
"<EXCEPTION>
<![CDATA[
]]>
</EXCEPTION>"

**Comment by hasanbirol89** [comment]
"EXCEPTION<![CDATA[]]/EXCEPTION

**Comment by hasanbirol89** [comment]
EXCEPTION<![CDATA[]]/EXCEPTION

**Comment by cowtowncoder** [comment]
How would you expect anyone to reproduce your problem with just a description of error message?

Please include a reproduction, code, class(es) involved, Jackson version used.

**Comment by hasanbirol89** [comment]
I cant share the fulll xml. Because, it is disallowed by Github. I am using these versions. 

<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-xml</artifactId>
    <version>2.9.8</version>
</dependency>

**Comment by hasanbirol89** [comment]
I guess I should use it with woodstox ?

**Comment by hasanbirol89** [comment]
@cowntowncoder

I found a workaround. I was writing any exception with CDATA.
Now, I am using with xmlMapper.writeValueAsString(exception)

Thanks.

**Comment by cowtowncoder** [comment]
@hasanbirol89 sharing full xml should not matter, although a subset to help reproduce the problem would be needed. And yes, use of Woodstox is recommended (although Aalto also works well); default Stax impl that comes with JDK has historically had more issues unfortunately.
