### ISSUE TITLE
InputCoercionException encountered in Jackson version 2.10.0.pr1

### ISSUE THREAD

**Issue by EricWittmann** [FasterXML/jackson-core#550]
After upgrading to jackson version 2.10.0.pr1 we are seeing a `InputCoercionException` when parsing some JSON.  I don't have a reproducer yet, as this is buried a bit in our system, but I'll work on that and report back here if I can come up something.  Specifically the error is:

```
com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (1565117390586) out of range of long (-9223372036854775808 - 9223372036854775807)
```

**Comment by EricWittmann** [comment]
Note: I saw there were some changes in this area when I diff'd version 2.10.0.pr1 with 2.9.9.  fwiw

**Comment by EricWittmann** [comment]
Here is a simple reproducer:

[my-app.zip](https://github.com/FasterXML/jackson-core/files/3473850/my-app.zip)

**Comment by cowtowncoder** [comment]
I think this might be due to #2393, fixed for 2.10.0.pr2.

**Comment by cowtowncoder** [comment]
Looking at reproduction I feel confident it is the same root cause; leaving open for validation.

**Comment by jiangyoudi** [comment]
**After upgrading to jackson version 2.10.0 or 2.10.1  from 2.3.3, we are seeing a InputCoercionException when parsing some JSON.**

SEVERE: Servlet.service() for servlet [Spring-MVC] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Could not decode JSON] with root cause
com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (1530676465000) out of range of int (-2147483648 - 2147483647)
 at [Source: (String)"{"_class":"com.cmcc.devicesman.entity.AccessTokenDevicesV2","account":{"createTime":1530676465000,"accountId":14,"isCorp":1,"status":2,"type":1,"password":"fc104baa74916203b549897e1acd371c","isCardPlatformEnabled":false,"email":"AndLink@prod.com","isPlatformEnabled":false,"mid":"ADL66","devKey":"FuJs0zgQ9BMfy1XuHhuzU8etvUInvgv8","marsterKey":"12345678"},"type":"DEVELOPER_KEY","key":"FuJs0zgQ9BMfy1XuHhuzU8etvUInvgv8"}"; line: 1, column: 98]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInputCoercion(ParserMinimalBase.java:601)
	at com.fasterxml.jackson.core.base.ParserMinimalBase.reportOverflowInt(ParserMinimalBase.java:570)
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:889)
	at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:802)
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:646)
	at com.fasterxml.jackson.core.base.ParserMinimalBase.getValueAsInt(ParserMinimalBase.java:365)
	at org.springframework.data.couchbase.core.convert.translation.JacksonTranslationService.decodePrimitive(JacksonTranslationService.java:223)
	at org.springframework.data.couchbase.core.convert.translation.JacksonTranslationService.decodeObject(JacksonTranslationService.java:168)
	at org.springframework.data.couchbase.core.convert.translation.JacksonTranslationService.decodeObject(JacksonTranslationService.java:162)
	at org.springframework.data.couchbase.core.convert.translation.JacksonTranslationService.decode(JacksonTranslationService.java:133)
	at org.springframework.data.couchbase.core.CouchbaseTemplate.translateDecode(CouchbaseTemplate.java:132)
	at org.springframework.data.couchbase.core.CouchbaseTemplate.findById(CouchbaseTemplate.java:185)
	at org.springframework.data.couchbase.repository.support.SimpleCouchbaseRepository.findOne(SimpleCouchbaseRepository.java:101)

**Comment by jiangyoudi** [comment]
After upgrading to jackson version 2.10.0 or 2.10.1 from 2.3.3, we are seeing a InputCoercionException when parsing some JSON.

SEVERE: Servlet.service() for servlet [Spring-MVC] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Could not decode JSON] with root cause
com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (1530676465000) out of range of int (-2147483648 - 2147483647)
at [Source: (String)"{"_class":"com.cmcc.devicesman.entity.AccessTokenDevicesV2","account":{"createTime":1530676465000,"accountId":14,"isCorp":1,"status":2,"type":1,"password":"fc104baa","isCardPlatformEnabled":false,"email":"XXX@com","isPlatformEnabled":false,"mid":"ADL66","devKey":"FuJs0zgXXXXXXXXXXXX","marsterKey":"12345678"},"type":"XXXXXXX","key":"XXXXXXXXX"}"; line: 1, column: 98]
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInputCoercion(ParserMinimalBase.java:601)
at com.fasterxml.jackson.core.base.ParserMinimalBase.reportOverflowInt(ParserMinimalBase.java:570)
at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:889)
at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:802)
at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:646)
at com.fasterxml.jackson.core.base.ParserMinimalBase.getValueAsInt(ParserMinimalBase.java:365)
at org.springframework.data.couchbase.core.convert.translation.JacksonTranslationService.decodePrimitive(JacksonTranslationService.java:223)
at org.springframework.data.couchbase.core.convert.translation.JacksonTranslationService.decodeObject(JacksonTranslationService.java:168)
at org.springframework.data.couchbase.core.convert.translation.JacksonTranslationService.decodeObject(JacksonTranslationService.java:162)
at org.springframework.data.couchbase.core.convert.translation.JacksonTranslationService.decode(JacksonTranslationService.java:133)
at org.springframework.data.couchbase.core.CouchbaseTemplate.translateDecode(CouchbaseTemplate.java:132)
at org.springframework.data.couchbase.core.CouchbaseTemplate.findById(CouchbaseTemplate.java:185)
at org.springframework.data.couchbase.repository.support.SimpleCouchbaseRepository.findOne(SimpleCouchbaseRepository.java:101)

**Comment by jiangyoudi** [comment]
` public int getValueAsInt() throws IOException
    {
        **_JsonToken t = _currToken;
        if ((t == JsonToken.VALUE_NUMBER_INT) || (t == JsonToken.VALUE_NUMBER_FLOAT)) {
            return getIntValue();
        }_**
        return getValueAsInt(0);
    }`

this code is 2.10.1 version of  ParserMinimalBase.java 。if i delete this code,function is ok still?

**Comment by cowtowncoder** [comment]
@jiangyoudi I am not sure I understand your question.

But if you have a specific problem, even if it looks similar to something in a closed issue, please file a new issue. It may be different, and I rarely open issues that were mark as closed (doing so will make release notes confusing).

If you do file a new issue, please include problem reproduction (sample code, unit test).
