### ISSUE TITLE
Connot use JsonReadFeature with yamlFactory

### ISSUE THREAD

**Issue by jflefebvre06** [FasterXML/jackson-core#608]
```java
YAMLFactory.builder().enable(Feature.MINIMIZE_QUOTES).disable(Feature.USE_NATIVE_TYPE_ID).disable(Feature.WRITE_DOC_START_MARKER).disable(Feature.SPLIT_LINES)
                .disable(JsonReadFeature.ALLOW_MISSING_VALUES).disable(JsonReadFeature.ALLOW_TRAILING_COMMA).build()
```

```console
java.lang.IllegalArgumentException: Feature com.fasterxml.jackson.core.json.JsonReadFeature#ALLOW_MISSING_VALUES not supported for non-JSON backend
	at com.fasterxml.jackson.core.TSFBuilder._failNonJSON(TSFBuilder.java:227)
	at com.fasterxml.jackson.core.TSFBuilder.disable(TSFBuilder.java:214)
	at com.wac.core.ant.utils.JacksonUtil.getYamlMapper(JacksonUtil.java:428)
	at com.wac.core.ant.utils.JacksonUtil.getYamlMapper(JacksonUtil.java:343)
	at com.wac.core.ant.task.configuration.models.versions.AbstractModelUTCase.internalUnmalshall(AbstractModelUTCase.java:103)
	at com.wac.core.ant.task.configuration.models.versions.AbstractModelUTCase.unmalshall(AbstractModelUTCase.java:127)
	at com.wac.core.ant.task.configuration.models.versions.v010000.GlobalConfUT.collectionsNotNullTest(GlobalConfUT.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:115)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:115)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)


```

**Comment by cowtowncoder** [comment]
Correct: as name says, it is `JsonReadFeature`, specific to JSON backend. Do not try to use it with YAML (YAML-specific ones would be in `YAMLParser.Feature`).

**Comment by jflefebvre06** [comment]
Could you please give me an example

**Comment by cowtowncoder** [comment]
@jflefebvre06 Example of what specifically?

To get rid of exception: do not try to set a `JsonReadFeature` on YAML parser, drop that part. That will get rid of exception. Setting was not doing anything before, either, as it is and was only supported by JSON-reading parser (but was included as part of API due to historical reasons).

On setting YAMLParser.Feature's: actually looking at `YAMLParser`, none are defined yet (there are couple of `YAMLGenerator.Feature`s that are specific to YAML handling).

**Comment by jflefebvre06** [comment]
My current code is 

```java
final YAMLMapper mapper = new YAMLMapper(yamlFactory);
mapper.enable(JsonParser.Feature.STRICT_DUPLICATE_DETECTION)
.disable(JsonParser.Feature.ALLOW_MISSING_VALUES).disable(JsonParser.Feature.ALLOW_TRAILING_COMMA);
```

I would like to replace `JsonParser.Feature.ALLOW_MISSING_VALUES` and `JsonParser.Feature.ALLOW_TRAILING_COMMA` which are deprecated

**Comment by cowtowncoder** [comment]
Ah. So, there is matching `StreamReadFeature` in 2.10, so to get rid of warnings, you will need to create factory like so:

```
        JsonFactory dupF = JsonFactory.builder()
                .enable(StreamReadFeature.STRICT_DUPLICATE_DETECTION)
                .build();
```

but you can still also use old `JsonParser.Feature` equivalents if you want. They will not be removed before Jackson 3.0.

So: 2.x used to only have `JsonParser.Feature`, but starting with 2.0, these will be split into two replacements:

1. `StreamReadFeature`s that work on all (or at least most) dataformats.
2. per-format features (for JSON, `JsonReadFeature`), only applicable to that format

To retain backwards compatibility, however, existing `JsonParser.Feature`s will be still supported, and mapped to one of 2 above choices.

I hope this makes more sense.

**Comment by jflefebvre06** [comment]
Thanks a lot @cowtowncoder
