### ISSUE TITLE
Cannot deserialize enum field

### ISSUE THREAD

**Issue by awildturtok** [FasterXML/jackson-core#636]
Using Jackson 2.11.2 (and prior), enum fields fail to deserialize, I've tried to create a minimal test below:

```{java}
public enum AnEnum{
	AnEntry
}

class EnumFieldFailingTest {

	public static class AnObject {
		private final AnEnum field;

		@JsonCreator
		public AnObject(AnEnum when) {
			this.field = when;
		}
	}

	private final String text = "{ \"field\" : \"AnEntry\" }";


	@Test
	public void tryLoad() throws JsonProcessingException {
		ObjectMapper mapper = io.dropwizard.jackson.Jackson.newObjectMapper();

		mapper.readValue(text, AnObject.class);
	}
}
```

```{log}
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.bakdata.conquery.integration.json.AnEnum` from String "field": field was not one of [AnEntry]
 at [Source: (String)"{ "field" : "AnEntry" }"; line: 1, column: 3]

	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1702)
	at io.dropwizard.jackson.FuzzyEnumModule$PermissiveEnumDeserializer.deserialize(FuzzyEnumModule.java:59)
	at io.dropwizard.jackson.FuzzyEnumModule$PermissiveEnumDeserializer.deserialize(FuzzyEnumModule.java:37)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1315)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.bakdata.conquery.integration.json.EnumFieldFailingTest.tryLoad(EnumFieldFailingTest.java:26)```


It seems like ther Parser passed to PermissiveEnumDeserializer is advanced once before being passed in?

**Comment by cowtowncoder** [comment]
Wrong repo, will move.
