### ISSUE TITLE
java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonKey

### ISSUE THREAD

**Issue by jchambers-ln** [FasterXML/jackson-core#660]
After upgrading from 2.11.3 to 2.12.0 I am seeing the following error under Centos 7 (seems to work fine under windows).  The only change being updating the pom file to use 2.12.0 of jackson-databind, jackson-dataformat-csv, jackson-dataformat-xml, and jackson-core -- I couldn't find anything in the change log defining a change in this area.  Reverting back to 2.11.3 it worked again, I also built the project with 2.11.4 and that also works.

```
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonKey
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[ln-mini-apps-ws-2.6.0-SNAPSHOT.jar:2.6.0-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
        at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.hasAsKey(JacksonAnnotationIntrospector.java:1080) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:451) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:378) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:343) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:190) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:323) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:272) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:223) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:261) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:150) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:591) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4731) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4592) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3546) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3514) ~[jackson-databind-2.12.0.jar!/:2.12.0]
        ```

**Comment by jchambers-ln** [comment]
Seems in 2.12 you have to specifically add the dependency if using maven to include annotation but didn't in previous versions-- probably worth adding to the change log.


<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.12.0</version>
</dependency>

**Comment by cowtowncoder** [comment]
I can't think of any change to `jackson-databind` pom that would do this -- but I think your problem is not that `jackson-annotations` dependency is missing but that somehow you get an older version: `@JsonKey` was added in 2.12. Jackson 2.11 did not add any new types (and 2.10 only some properties).
So it seems likely that somehow you have inconsistent sets of versions, seemingly older `jackson-annotations` than `jackson-databind`.

So you may want to check how dependencies are defined. Part of this may also be wrt Maven dependency version resolution: although `jackson-databind` does have dependency to correct matching version of `jackson-annotations` and `jackson-core`, these are transitive dependencies and any direct dependencies would override version. And possibly alternate transitive dependencies as well; logic in those cases gets more convoluted. If using Maven as build, you can use:

    mvn dependency:tree

to see where various versioned dependencies come from -- and see whether my guess is correct wrt earlier versions (that it may have just happened to work since jackson-databind 2.11 did not absolutely require annotations 2.11).

**Comment by jchambers-ln** [comment]
Makes sense the project where this occurred has a very complex POM at this point.  I think this can close out.  Hopefully if someone else hits it this will show up in their google search and help them.  It threw me since it was a single version update that triggered it I wasn't expecting it... especially since it passed all the tests on windows but failed in centos which didn't make me think the dependency tree at first.

**Comment by cowtowncoder** [comment]
@jchambers-ln agreed, I doubt you are the only person who is hit by similar or same issue.

On Windows vs Centos, that could actually point to slightly different variation: existence of 2 versions of same artifact; or just in general ordering of jars in classpath. Even worse are cases where some library might shade in Jackson artifacts without relocation, although `jackson-annotations` really never should be shaded (but may end up, esp. when embedded automatically as transitive dependency). But I guess first things first; just eliminating simpler case of of old version being found.
