### ISSUE TITLE
`FilteringParserDelegate` cannot deserialize empty list

### ISSUE THREAD

**Issue by xiazuojie** [FasterXML/jackson-core#708]
This is a follow up issue of https://github.com/FasterXML/jackson-core/issues/700 .

If using FilteringParserDelegate to filter out a part of json, it throws the following exception when the input json is an empty list ("[]").

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])"[]"; line: 1, column: 2]

	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4688)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4561)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2823)
	at com.alibaba.dapr.serialization.json.FilteringParserDelegateTest.testFilteringParserDelegateWithEmptyList(FilteringParserDelegateTest.java:36)
```
Test case:
```java
package com.alibaba.dapr.serialization.json;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.filter.FilteringParserDelegate;
import com.fasterxml.jackson.core.filter.TokenFilter;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.assertTrue;

public class FilteringParserDelegateTest {
    @Test
    public void testFilteringParserDelegateWithEmptyList() throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        final TokenFilter tokenFilter = new TokenFilter() {
            @Override
            public TokenFilter includeProperty(String name) {
                if ("@type".equals(name)) {
                    return null;
                }
                return INCLUDE_ALL;
            }
        };

        byte[] content = "[]".getBytes(StandardCharsets.UTF_8);

        JsonParser jp = mapper.createParser(content);
        JsonParser jsonParser = new FilteringParserDelegate(jp, tokenFilter, TokenFilter.Inclusion.INCLUDE_ALL_AND_PATH, true);

        List<Map<String, String>> a = mapper.readValue(jsonParser, new TypeReference<List<Map<String, String>>>() {});
        assertTrue(a.isEmpty());
    }
}

```
Jackson version: 2.12.3

**Comment by cowtowncoder** [comment]
Interesting... empty array (and empty Object) are sort of edge cases since they are leaf values on their own.

Will need to think of what to do with them; almost certainly need to add 2 more callback methods in `TokenFilter`.
I hope to be able to fix this before 2.13.0 final but that may take time.

Will add failing tests first.

**Comment by cowtowncoder** [comment]
Interesting. I can see performance benefits for both Jackson and fast-json for "collect single value" case (no change for gson); that makes sense. For Jackson almost 2x as high, for fast-json 10-20%.

I did not see much change for "large json" but that might be since overhead of not closing is relatively smaller.

I hope to have time to run async-profiler for both cases too, to see if large json cases is working as expected.
Since input is 10 meg json document overhead should matter way less than for smaller docs. But I am bit surprised that gson would be faster than jackson or fast-json there.

This seems like a really good progress!

**Comment by cowtowncoder** [comment]
Resolved via #715, to be included in 2.14.0. Closing this as dup (just for convenience as PR was pointing to the other issue).

**Comment by cowtowncoder** [comment]
Looks like this was NOT fully resolved -- will reopen.

**Comment by cowtowncoder** [comment]
Fixed for 2.21.0, 3.0.2.
