### ISSUE TITLE
@JsonValue drops subterms

### ISSUE THREAD

**Issue by Wouter1** [FasterXML/jackson-core#913]
I get exceptions and sub-terms disappear when I use @JsonValue.

Here is the code to reproduce
```
package test.java;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class test {
	final ObjectMapper jackson = new ObjectMapper();
	final N n = new N();

	@Test
	public void test1() throws JsonProcessingException {
		doTest(new Y(n));
	}

	@Test
	public void test2() throws JsonProcessingException {
		doTest(new Y(new Y(n)));
	}

	@Test
	public void testWeirdYDisappears() throws JsonProcessingException {
		doTest(new Z(new Y(n)));
	}

	@Test
	public void testFails() throws JsonProcessingException {
		doTest(new Z(n));
	}

	private void doTest(X val) throws JsonProcessingException {
		System.out.println("testing " + val);
		String str = jackson.writeValueAsString(val);
		System.out.println("To json: " + str);
		X obj = jackson.readValue(str, X.class);
		System.out.println("reparsed: " + obj);

		assertEquals(val.toString(), obj.toString());

	}
}

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.WRAPPER_OBJECT)
@JsonAutoDetect(fieldVisibility = Visibility.ANY, getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE)
@JsonSubTypes({ @JsonSubTypes.Type(value = Y.class),
		@JsonSubTypes.Type(value = Z.class),
		@JsonSubTypes.Type(value = N.class) })
interface X {
}

class N implements X {

	@Override
	public String toString() {
		return "N";
	}

}

class Y implements X {

	// NOT @JsonValue - works
	private final X value;

	@JsonCreator
	public Y(@JsonProperty("value") X val) {
		this.value = val;
	}

	@Override
	public String toString() {
		return "Y(" + value + ")";
	}

}

class Z implements X {
	@JsonValue
	private final X value;

	@JsonCreator
	public Z(@JsonProperty("value") X val) {
		this.value = val;
	}

	@Override
	public String toString() {
		return "Z(" + value + ")";
	}

}
```. 
with pom
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>test</groupId>
	<artifactId>test</artifactId>
	<version>2.1</version>
	<packaging>jar</packaging>

	<name>test</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.target>1.8</maven.compiler.target>
		<maven.compiler.source>1.8</maven.compiler.source>
		<basedir>.</basedir>
		<jackson-2-version>2.14.2</jackson-2-version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>${jackson-2-version}</version>
		</dependency>

		
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>${jackson-2-version}</version>
		</dependency>

		
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson-2-version}</version>
		</dependency>

		
		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-smile</artifactId>
			<version>${jackson-2-version}</version>
		</dependency>
		
		<dependency>
			<groupId>com.fasterxml.jackson.jaxrs</groupId>
			<artifactId>jackson-jaxrs-json-provider</artifactId>
			<version>${jackson-2-version}</version>
		</dependency>
		
		<dependency>
			<groupId>com.fasterxml.jackson.module</groupId>
			<artifactId>jackson-module-jaxb-annotations</artifactId>
			<version>${jackson-2-version}</version>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-all</artifactId>
			<version>1.9.5</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>

	</dependencies>

	<build>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>3.1.0</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>

	</build>

</project>

```



output:
```
testing Z(N)
To json: {"Z":{}}
-exception

testing Z(Y(N))
To json: {"Z":{"value":{"N":{}}}}
-exception

testing Y(N)
To json: {"Y":{"value":{"N":{}}}}
reparsed: Y(N)
- success

testing Y(Y(N))
To json: {"Y":{"value":{"Y":{"value":{"N":{}}}}}}
reparsed: Y(Y(N))
-success
```

The Z(...) all fail with excceptions, like
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (END_OBJECT), expected START_OBJECT: need JSON Object to contain As.WRAPPER_OBJECT type information for class test.java.X
 at [Source: (String)"{"Z":{}}"; line: 1, column: 7]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:1944)
	at com.fasterxml.jackson.databind.DeserializationContext.reportWrongTokenException(DeserializationContext.java:1678)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:100)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:52)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1398)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:121)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:52)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
	at test.java.test.doTest(test.java:45)
	at test.java.test.testFails(test.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at j...
```


As you can see, the Z(N) when serialized has no N term anymore,
and the Z(Y(N)) term after serialization has not Y(N) but only N

I would expect Z(n) to serialize to json as ```{"Z":{"N":{}}}```
and Z(Y(n)) as ```{"Z":{"Y":{"value":{"N":{}}}}}```

If I use Y instead of Z, which does not have the @JsonValue annotation, it works all fine.

Not sure if it's relevant but something changed recently around @JsonValue so this may be a flawed bug fix,  @JsonValue is a troublesome area for a long time. There previously were issues when used in combination with List where jackson failed to add TypeInfo if it was needed. And previously you had to omit @JsonProperty annotations in the constructor when using together with @JsonValue.

**Comment by Wouter1** [comment]
If you change class Z to 
```
class Z implements X {
	@JsonValue
	private final X value;

	@JsonCreator
	public Z(@JsonProperty("value") X value) {
		this.value = value;
	}

	@Override
	public String toString() {
		return "Z(" + value + ")";
	}

}
```

the exceptions from the parser are gone. (I'm not sure why, I thought that the actual var name was irrelevant, why else have the annotation.  But that's another issue)

Now you get  the "cleaner" behaviour where the subterms of Z directly disappear

```
testing Z(N)
To json: {"Z":{}}
reparsed: Z(null)
testing Z(Y(N))
To json: {"Z":{"value":{"N":{}}}}
reparsed: Z(N)
```

**Comment by Wouter1** [comment]
Today I tried to work around this with a getter, by adding a getValue to the class and putting @JsonValue to that instead of the field. Like this

```
@JsonAutoDetect(fieldVisibility = Visibility.ANY)
class W implements X {
	private final X value;

	@JsonCreator
	public W(@JsonProperty("value") X value) {
		this.value = value;
	}

	@JsonValue
	public X getValue() {
		return value;
	}

	@Override
	public String toString() {
		return "W(" + value + ")";
	}

}

```

However it gives exactly the same problems, when I test with W(N)

**Comment by Wouter1** [comment]
@cowtowncoder  
Could you please have at least a short look at this to see if I'm doing anything stupid?
@JsonValue is I think an important feature of jackson and having this not working seems a major issue. I don't know any workaround.

**Comment by Wouter1** [comment]
I also tried various versions of jackson but from 2.9 they all have this issue.
Before 2.9 @JsonValue was used in a different way, probably only allowed at a getter.
If I try W(N) in 2.8.2 I get even weirder results where the TOP class disappears:
```
testing W(N)
To json: {"N":{}}
reparsed: N
```

**Comment by cowtowncoder** [comment]
@Wouter1 Unfortunately I have so many things to look at, and this example is rather long so I don't really have time to look into this.

But what I can do is move this to right repo: jackson-core is for streaming parser/generator; this belongs under `jackson-databind`.
Maybe others can help you here.
